#pragma once

#include "NativeGameplayTags.h"

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Input_Move);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Input_Dash);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Input_Aim);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Data_Damage)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_GameplayEvent_Damaged);
